### PR TITLE
Fix Thaumic Augmentation

### LINKED ISSUE #13746: Thaumic Augmentation doesn't work (SuperTiC)
### Your GTNH Discord Username

sheodar

### Your Pack Version

2.3.2

### Your Server

SP

### Java Version

Java 8

### Type of Server

Single Player

### Your Expectation

I'm trying to add +1 modifier for tinkers' tool (hammer). This infusion ritual should add +1 modifier.
image
image

### The Reality

Nothing happen. Ritual doesn't start.

### Your Proposal

Ritual +1 modifier for tinkers' tools doesnt' work.
Mod: SuperTiC.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

### LINKED ISSUE #14268: Thaumic Augmentation Matrix Recipe Not Working
### Your GTNH Discord Username

TheBronzeKnee

### Your Pack Version

2.3.6

### Your Server

Private Server

### Java Version

Java 8

### Type of Server

Vanilla Forge

### Your Expectation

Attempting to add an extra modifier to tinker's tools with the 2 jeweled apples and 1 block of manyullyn does not work.

### The Reality

Attempting to use the thaumic augmentation on any tinker's tool doesn't work. Tried with full durability and not full with no results, recipe just doesn't work. Was told this was a known issue by Alastor in the discord, and was asked to create an issue for it. It specifically cannot start the matrix ritual with all materials present.

### Your Proposal

Fix the damn recipe or else I'll mega blast furnace your house.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

### PR DESCRIPTION
**Pull request by chochem**
three fixes here:
- inconsistent spelling making research detection impossible
- recipes are never added to TCs recipe map
- missing copies resulted in a doubled effect

~However this only works with one more fix in Salis Arcana here https://github.com/rndmorris/Salis-Arcana/pull/380.~

This fixes https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/14268 and fixes https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/13746

### CODE REVIEW

**Comment by Dream-Master** [comment]
sadly we dont use much of super tic because the config was never touched i guess

**Comment by chochem** [comment]
actually seems like I can fix it fully (well really: finish the feature)

**Comment by chochem** [comment]
testing it on zeta is not going to do much unless you also include a salis arcana pre of sorts. (it doesnt break anything either though)

**Comment by Dream-Master** [comment]
> testing it on zeta is not going to do much unless you also include a salis arcana pre of sorts. (it doesnt break anything either though)

i caould add it but since i use upstream i not make any pres

File: src/main/java/com/Zoko061602/SuperTic/compat/InfusionModifierRecipe.java [hunk 1]
```diff
@@ -68,14 +69,15 @@ public boolean matches(ArrayList<ItemStack> input, ItemStack in, World world, En
...
+            NBTTagCompound nbt = out.getTagCompound();
             nbt.setBoolean("STicTC", true);
             int mod = nbt.getCompoundTag("InfiTool").getInteger("Modifiers") + 1;
             nbt.getCompoundTag("InfiTool").setInteger("Modifiers", mod);
-            input.setTagCompound(nbt);
+            out.setTagCompound(nbt);
         }
-        return input;
+        return out;
     }
```
Comment (Nikolay-Sitnikov) [inline src/main/java/com/Zoko061602/SuperTic/compat/InfusionModifierRecipe.java:71]: Why is `getRecipeOutput` just a direct copy of `getOutput`. Have `getRecipeOutput` redirect to `getOutput`, or something.

**Review by Nikolay-Sitnikov — DISMISSED** [review]

File: src/main/java/com/Zoko061602/SuperTic/compat/InfusionModifierRecipe.java (hunk 1 above)
Comment (chochem) [reply src/main/java/com/Zoko061602/SuperTic/compat/InfusionModifierRecipe.java:71]: *why* is a question I have long stopped asking for old code. done.

**Comment by chochem** [comment]
redid my testing and it all works now without any extra changes.

image

File: src/main/java/com/Zoko061602/SuperTic/compat/InfusionModifierRecipe.java [hunk 2]
```diff
@@ -28,14 +28,15 @@ public class InfusionModifierRecipe extends InfusionRecipe {
     private static Object getOutput(ItemStack input) {
         if (input == null) return null;
         if (input.getItem() == null) return null;
-        if (input.getItem() instanceof ToolCore) if (input.getTagCompound() != null) {
-            NBTTagCompound nbt = input.getTagCompound();
+        ItemStack out = input.copy();
+        if (out.getItem() instanceof ToolCore) if (out.getTagCompound() != null) {
```
Comment (Nikolay-Sitnikov) [inline src/main/java/com/Zoko061602/SuperTic/compat/InfusionModifierRecipe.java]:
```suggestion
        if (out.getItem() instanceof ToolCore && out.getTagCompound() != null) {
```

File: src/main/java/com/Zoko061602/SuperTic/compat/InfusionModifierRecipe.java [hunk 3]
```diff
@@ -28,14 +28,15 @@ public class InfusionModifierRecipe extends InfusionRecipe {
     private static Object getOutput(ItemStack input) {
         if (input == null) return null;
         if (input.getItem() == null) return null;
```
Comment (Nikolay-Sitnikov) [inline src/main/java/com/Zoko061602/SuperTic/compat/InfusionModifierRecipe.java]:
```suggestion
        if (input == null || input.getItem() == null) return null;
```

**Review by Nikolay-Sitnikov — CHANGES_REQUESTED** [review]
Some code formatting inconsistencies while I look for bigger flaws.

File: src/main/java/com/Zoko061602/SuperTic/compat/Thaumcraft.java [hunk 4]
```diff
@@ -66,8 +69,13 @@ static void registerRecipes() {
...
             applehard = new ItemStack(TinkerArmor.diamondApple);
         }
+        @SuppressWarnings("unchecked")
+        List<Object> recipes = ThaumcraftApi.getCraftingRecipes();
         infusion = new InfusionModifierRecipe(new ItemStack(tools[0]));
-        for (int i = 1; !(i == tools.length); i++) new InfusionModifierRecipe(new ItemStack(tools[i]));
+        recipes.add(infusion);
+        for (int i = 1; !(i == tools.length); i++) {
+            recipes.add(new InfusionModifierRecipe(new ItemStack(tools[i])));
+        }
```
Comment (Nikolay-Sitnikov) [inline src/main/java/com/Zoko061602/SuperTic/compat/Thaumcraft.java:78]:
```suggestion
        infusion = new InfusionModifierRecipe(new ItemStack(TinkerTools.pickaxe));
        recipes.add(infusion);
```

Not 100% sure this will work, but I am about 99% sure that registering one recipe will be enough to handle every single tool.

This will also allow the `tools` constant to be removed.

File: src/main/java/com/Zoko061602/SuperTic/compat/Thaumcraft.java
Comment (Nikolay-Sitnikov) [inline src/main/java/com/Zoko061602/SuperTic/compat/Thaumcraft.java]:
```suggestion
```
This can be removed.

**Review by Nikolay-Sitnikov — COMMENTED** [review]
Could you test this for me, please?

File: src/main/java/com/Zoko061602/SuperTic/compat/Thaumcraft.java (hunk 4 above)
Comment (chochem) [reply src/main/java/com/Zoko061602/SuperTic/compat/Thaumcraft.java:78]: it would certainly remove them from NEI, though its not like this works perfectly with NEI anyway

File: src/main/java/com/Zoko061602/SuperTic/compat/InfusionModifierRecipe.java [hunk 5]
```diff
@@ -26,16 +26,16 @@ public class InfusionModifierRecipe extends InfusionRecipe {
...
-        if (input == null) return null;
-        if (input.getItem() == null) return null;
-        if (input.getItem() instanceof ToolCore) if (input.getTagCompound() != null) {
-            NBTTagCompound nbt = input.getTagCompound();
+        if (input == null || input.getItem() == null) return null;
+        ItemStack out = input.copy();
+        if (out.getItem() instanceof ToolCore && out.getTagCompound() != null) {
+            NBTTagCompound nbt = out.getTagCompound();
             nbt.setBoolean("STicTC", true);
             int mod = nbt.getCompoundTag("InfiTool").getInteger("Modifiers") + 1;
```
Comment (Nikolay-Sitnikov) [inline src/main/java/com/Zoko061602/SuperTic/compat/InfusionModifierRecipe.java:34]: Do you think we should check for the case where a blank Tinker's Construct tool somehow exists without an `InfiTool` tag?

**Review by Nikolay-Sitnikov — APPROVED** [review]
